- Smartway.UiComponent.Sample/SectionSheet/Views/SectionSheetSample.xaml
- Smartway.UiComponent/CardLists/ArticleCardList.xaml
- Smartway.UiComponent/CardLists/ArticleCardList.xaml.cs
> Adapt ArticleCardList To Condensed Card option

- Smartway.UiComponent.Sample/Basics/BasicComponents.xaml
- Smartway.UiComponent/Labels/PluralizableLabel.xaml
- Smartway.UiComponent/Labels/PluralizableLabel.xaml.cs
- Smartway.UiComponent/Smartway.UiComponent.csproj
j'ai reussi à le faire en un composant, si on passe un string dans les attributs `SingularForm` ou `PluralForm` avec un `{0}`, on récupère le nombre d'item, mais si on ne le met pas, ça marche aussi
> Add component PluralizableLabel

- Smartway.UiComponent/Cards/ArticleCard.xaml
> :bug: fix article cart label size

- Smartway.UiComponent.Droid/Renderers/CustomButtonRenderer.cs
- Smartway.UiComponent.Droid/Smartway.UiComponent.Droid.csproj
- Smartway.UiComponent/Buttons/Button.xaml
> :sparkles: add custom renderer for disabled button

- Smartway.UiComponent.Sample/MainPage.xaml
- Smartway.UiComponent.Sample/MainPageViewModel.cs
- Smartway.UiComponent.Sample/Pages/ModalPageSample.xaml
- Smartway.UiComponent.Sample/Pages/ModalPageSample.xaml.cs
- Smartway.UiComponent.Sample/Smartway.UiComponent.Sample.csproj
- Smartway.UiComponent/Pages/ModalPage.xaml
- Smartway.UiComponent/Pages/ModalPage.xaml.cs
- Smartway.UiComponent/Smartway.UiComponent.csproj
> ModalPage Component

- Smartway.UiComponent.Sample/Buttons/Button.xaml
- Smartway.UiComponent/Buttons/Button.xaml
- Smartway.UiComponent/Buttons/Button.xaml.cs
- Smartway.UiComponent/Buttons/ScanButton.xaml
- Smartway.UiComponent/Buttons/TextButton.xaml
- Smartway.UiComponent/Buttons/TextButton.xaml.cs
- Smartway.UiComponent/Smartway.UiComponent.csproj
> Text Buttons + Buttons improvments

- Smartway.UiComponent.Sample/Inputs/ViewModels/InputsViewModel.cs
- Smartway.UiComponent.Sample/Inputs/Views/Inputs.xaml
- Smartway.UiComponent/Inputs/Chips.xaml
- Smartway.UiComponent/Inputs/Chips.xaml.cs
- Smartway.UiComponent/Smartway.UiComponent.csproj
Le composant lié: https://xd.adobe.com/view/819247d5-d6ce-4c21-bf8e-fb60c2b8712e-d4c1/screen/1efa710a-4616-486e-8f0e-952b13dabbce/specs/
> ✨Choice chips component

- Smartway.UiComponent.Sample/Inputs/ViewModels/FormEntryViewModel.cs
- Smartway.UiComponent.Sample/Inputs/Views/FormEntry.xaml
- Smartway.UiComponent.Sample/Inputs/Views/FormEntry.xaml.cs
- Smartway.UiComponent.Sample/MainPageViewModel.cs
- Smartway.UiComponent/Inputs/FormEntry.xaml
- Smartway.UiComponent/Inputs/FormEntry.xaml.cs
- Smartway.UiComponent/TopAppBar/TopAppBar.xaml
(J'ai voulu mettre le deuxième commit dans une branche à part, mais plus rien marcher, donc plutôt que d'éviter de passer 3H dessus, je l'ai laissé ici)
> 💄 Task/review top app bar

- Smartway.UiComponent.Sample/Indicators/Views/Indicators.xaml
- Smartway.UiComponent/Indicators/Status.xaml
- Smartway.UiComponent/Indicators/Status.xaml.cs
> ✨ Add new status colors

- Smartway.UiComponent.Sample.Android/CustomEntryRenderer.cs
- Smartway.UiComponent.Sample.Android/Resources/Resource.designer.cs
- Smartway.UiComponent.Sample/Inputs/Views/FormEntry.xaml
- Smartway.UiComponent.Sample/Inputs/Views/FormEntry.xaml.cs
- Smartway.UiComponent.Sample/MainPageViewModel.cs
- Smartway.UiComponent.Sample/Smartway.UiComponent.Sample.csproj
- Smartway.UiComponent/Inputs/FormEntry.xaml
- Smartway.UiComponent/Inputs/FormEntry.xaml.cs
> remove copy/paste bug, improve form entry and add password entry

- Smartway.UiComponent.Sample/Layouts/LayoutsSample.xaml
- Smartway.UiComponent/Layouts/ClickableItem.xaml
- Smartway.UiComponent/Layouts/ClickableItem.xaml.cs
- Smartway.UiComponent/Smartway.UiComponent.csproj
> ✨create ClickableItem

- Smartway.UiComponent.Sample/TopAppBar/Views/TopAppBar.xaml
- Smartway.UiComponent/TopAppBar/TopAppBar.xaml
- Smartway.UiComponent/TopAppBar/TopAppBar.xaml.cs
> 🐛 fix position label with no image

- Smartway.UiComponent/Labels/Icons/Icon.xaml.cs
- checkmark : https://material.io/resources/icons/?search=check&icon=check&style=baseline
- format align left : https://material.io/resources/icons/?search=format_&icon=format_align_left&style=baseline
- stop : https://material.io/resources/icons/?search=stop&icon=stop&style=baseline
- today : https://material.io/resources/icons/?search=cale&icon=today&style=baseline
- delete : https://material.io/resources/icons/?icon=delete&style=baseline
> Add missing icons

- Smartway.UiComponent.Sample/Inputs/ViewModels/InputsViewModel.cs
- Smartway.UiComponent.Sample/Inputs/Views/Inputs.xaml
- Smartway.UiComponent/Inputs/Counter.xaml
- Smartway.UiComponent/Inputs/Counter.xaml.cs
- Smartway.UiComponent/Smartway.UiComponent.csproj
> ✨ Add counter component

- Smartway.UiComponent.Sample/Inputs/ViewModels/InputsViewModel.cs
- Smartway.UiComponent.Sample/Inputs/Views/Inputs.xaml
- Smartway.UiComponent/Inputs/Counter.xaml
- Smartway.UiComponent/Inputs/Counter.xaml.cs
> :bug: Fix and improve counter component

- Smartway.UiComponent.Sample/Buttons/Button.xaml
- Smartway.UiComponent/Buttons/ToggleButton.xaml
- Smartway.UiComponent/Buttons/ToggleButton.xaml.cs
- Smartway.UiComponent/Smartway.UiComponent.csproj
> :sparkles: :lipstick: add toggle button

- Smartway.UiComponent.Sample/Inputs/ViewModels/InputsViewModel.cs
- Smartway.UiComponent.Sample/Inputs/Views/Inputs.xaml
- Smartway.UiComponent.UnitTests/Inputs/NumericInputTest.cs
- Smartway.UiComponent.UnitTests/Smartway.UiComponent.UnitTests.csproj
- Smartway.UiComponent/Inputs/NumericInput.xaml
- Smartway.UiComponent/Inputs/NumericInput.xaml.cs
- Smartway.UiComponent/Resources/Colors.xaml
- Smartway.UiComponent/Smartway.UiComponent.csproj
New version below : (je squasherai les commits si c'est validey)
> :sparkles: add double quantity component

- Smartway.UiComponent.UnitTests/Inputs/NumericInputTest.cs
- Smartway.UiComponent/Inputs/NumericInput.xaml.cs
> :bug: allow numeric input component to be empty

- Smartway.UiComponent/TopAppBar/TopAppBar.xaml
- Smartway.UiComponent/TopAppBar/TopAppBar.xaml.cs
> :recycle: :lipstick: TopAppBar - make text color bindable 

- Smartway.UiComponent.Sample/SectionSheet/ViewModels/SectionSheetSampleViewModel.cs
- Smartway.UiComponent.Sample/SectionSheet/Views/SectionSheetSample.xaml
- Smartway.UiComponent/Cards/ProductCard.xaml
- Smartway.UiComponent/Cards/ProductCard.xaml.cs
- Smartway.UiComponent/Resources/Colors.xaml
- Smartway.UiComponent/Smartway.UiComponent.csproj
> :sparkles: Add ProductCard component

- Smartway.UiComponent.Sample/SectionSheet/Views/SectionSheetSample.xaml
- Smartway.UiComponent/Cards/ProductCard.xaml
- Smartway.UiComponent/Cards/ProductCard.xaml.cs
- Smartway.UiComponent/Resources/Colors.xaml
> :sparkles: ProductCard - Add IsReadOnly property

- .github/workflows/xamarin-ui-build.yml
- .github/workflows/xamarin-ui-integration.yml
- .github/workflows/xamarin-ui-notify.yml
- .github/workflows/xamarin-ui-publish.yml
- .github/workflows/xamarin-ui-pullrequest.yml
- .github/workflows/xamarin-ui-release.yml
- Smartway.UiComponent.UnitTests/Smartway.UiComponent.UnitTests.csproj
- Creation of Build and Publish pipeline on Github Actions ochestrator
- Small modification on csproj file to have the capability to build Smartway.UiComponent.sln project with Xamarin-Android for Unix (Container)
Note: Don't merge without disabled Teamcity webhook
> 🚀 Create Xamarin UI Github Action CI
